# Generated by Django 5.1 on 2024-09-03 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodiee',
            old_name='desc',
            new_name='Desc',
        ),
    ]
