# Generated by Django 5.1 on 2024-10-12 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0007_remove_cart_product_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='user',
            new_name='cart',
        ),
    ]
