# Generated by Django 5.1 on 2024-09-07 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0002_rename_desc_foodiee_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.TextField()),
                ('cost', models.FloatField()),
                ('images', models.ImageField(upload_to='./Food/images/')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
